spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://grdtest-m.dbsit.sfdc.com.cn:3306/grdtest
    username: grdtest
    password: admin123
  thymeleaf:
    mode: HTML5
    cache: false
  servlet:
    multipart:
      max-file-size: 100MB
logging:
  config: classpath:config/logback.xml
  path: share/logs/ch-admin
  level:
    com:
      ch: debug
path:
  temp: share/tmp
  root: D:\\git\\ch-cloud-new\\ch-admin2
  upload: D:\\git\\ch-cloud-new\\ch-admin2\\upload
  download: share/download