server:
  port: 7002

jasypt:
  encryptor:
    password: abc123
    algorithm: PBEWithMD5AndDES
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.zhaohuajike.cn:3306/dev_ch_upms
    username: admin
    password: ENC(hfO3JFDCY2HB6x+j1obZOg==)
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  thymeleaf:
    mode: HTML
    cache: false
  servlet:
    multipart:
      max-file-size: 100MB
logging:
  config: classpath:config/logback.xml
  path: logs/${spring.application.name}
  level:
    com.ch: debug
    com.alibaba.nacos.client: warn

path:
  temp: share/tmp
  root: D:\\git\\ch-cloud-new\\ch-admin2
  upload: D:\\git\\ch-cloud-new\\ch-admin2\\upload
  download: share/download


rocketmq:
  name-server: 192.168.1.104:9876 # 自己的RocketMQ服务地址
  producer:
    send-message-timeout: 300000
    group: ch-upms