DROP TABLE IF EXISTS `st_user_role`;
CREATE TABLE `st_user_role` (
  `USER_ID` BIGINT(20) NOT NULL COMMENT '用户ID',
  `ROLE_ID` BIGINT(20) NOT NULL COMMENT '角色ID',
  `STATUS` CHAR(1) NOT NULL DEFAULT '0' COMMENT '状态：1.用户默认角色',
  PRIMARY KEY (`USER_ID`, `ROLE_ID`),
  KEY `IDX_ST_UR_ROLE_ID` (`ROLE_ID`)
) ENGINE = INNODB DEFAULT CHARSET=UTF8 COMMENT '用户角色表';

INSERT INTO st_user_role (USER_ID, ROLE_ID) VALUES (1, 1);