DROP TABLE IF EXISTS `lt_op_record`;
CREATE TABLE `lt_op_record` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `URL` VARCHAR(250) NULL COMMENT '请求地址',
  `METHOD` VARCHAR(50) NOT NULL COMMENT '请求方法',
  `REQUEST` text NULL COMMENT '请求信息',
  `PROXY` text NULL COMMENT '代理信息',
  `RESPONSE` text NULL COMMENT '响应信息',
  `AUTH_CODE` VARCHAR(255) NULL COMMENT '请求权限',
  `STATUS` int(10) NULL COMMENT '响应状态',
  `OPERATOR` VARCHAR(64) NULL COMMENT '请求用户',
  `REQUEST_TIME` TIMESTAMP NOT NULL COMMENT '请求时间',
  `RESPONSE_TIME` TIMESTAMP NOT NULL COMMENT '响应时间',
  PRIMARY KEY (`ID`),
  KEY `IDX_LT_OR_STATUS` (`STATUS`),
  KEY `IDX_LT_OR_OPERATOR` (`OPERATOR`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT '日志表-操作记录';