spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local   # 指定启动环境

# 开发环境
---
spring:
  profiles: local
test:
  env: local

# 测试环境
---
spring:
  profiles: test
test:
  env: test

# 仿生环境
---
spring:
  profiles: staging
test:
  env: staging

# 生产环境
---
spring:
  profiles: prod
test:
  env: prod
