#服务端口
server:
  port: 8082
  # servlet:
    # context-path: /upms
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1024MB
  datasource:
    url: jdbc:mysql://192.168.0.8:3306/admin?useSSL=false
    username: admin
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  thymeleaf:
    mode: HTML
    cache: false

logging:
  config: classpath:config/logback.xml
  path: logs/ch-admin
  level:
    com.ch: debug
    com.alibaba.nacos.client: warn
path:
  root: /mnt/share
  temp: /mnt/share/tmp
  upload: /Users/zhimin/work/oschina/ch-cloud/ch-admin2/upload
  download: /mnt/share/download