server:
  port: 7002
jasypt:
  encryptor:
    password: abc123
    algorithm: PBEWithMD5AndDES

#====================================shardingsphereconfig===============================================
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  shardingsphere:
    mode:
      type: Standalone
      repository:
        type: JDBC
        props:
          path: ./config/shardingsphere
          datasource-class-name: com.zaxxer.hikari.HikariDataSource
          jdbc-url: jdbc:mysql://192.168.150.254:3306/ch_wiki?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          username: zhimin
          password: 123456
    props:
      # 禁用执行SQL用于获取表元数据
      sql-show: true
      # 禁用执行SQL用于获取数据库元数据
    #      check-table-metadata-enabled: false
    datasource:
      names: ds0
      ds0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://192.168.1.86:3306/ch_wiki_dev?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: zhimin
        password: Zhimin@12345
    rules:
      sharding:
        sharding-algorithms:
          auto-date-algorithm:
            type: AUTO_INTERVAL
            props:
              datetime-lower: '2024-11-01 00:00:00'
              datetime-upper: '2024-12-31 23:59:59'
              sharding-seconds: 86400
          date-month-algorithm:
            type: INTERVAL
            props:
              datetime-pattern: yyyy-MM-dd
              datetime-lower: '2024-11-01'
              datetime-upper: '2099-12-31'
              sharding-suffix-pattern: yyyyMM
              datetime-interval-amount: 1
              datetime-interval-unit: MONTHS
        tables:
          lt_op_record:
            actualDataNodes: ds0.lt_op_record_$->{0..1}
            logicTable: lt_op_record
            table-strategy:
              standard:
                sharding-column: AUTH_CODE
                sharding-algorithm-name: date-month-algorithm
#====================================spring config===============================================
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
##    url: jdbc:mysql://106.12.140.185:3306/dev_ch_upms
##    username: admin
##    password: ENC(hfO3JFDCY2HB6x+j1obZOg==)
#    url: jdbc:mysql://192.168.0.109:3306/ch_upms?characterEncoding=UTF-8&serverTimezone=GMT
#    username: admin
#    password: 123456
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      minimum-idle: 5
#      maximum-pool-size: 15
#      auto-commit: true
#      idle-timeout: 30000
#      pool-name: DatebookHikariCP
#      connection-timeout: 30000
#      connection-test-query: SELECT 1
  thymeleaf:
    mode: HTML
    cache: false
  servlet:
    multipart:
      max-file-size: 100MB
  redis:
    host: 192.168.150.206
    port: 6379
    password: admin123
    database: 3
  cache:
    type: redis
    redis:
      key-prefix: upms_


management:
  health:
    db:
      enabled: false
logging:
  config: classpath:config/logback.xml
  level:
    com.ch.cloud: debug
    com.ch.utils: info
    com.alibaba.nacos.client: warn
  file:
    path: build/logs


#====================================rocketmq config===============================================
rocketmq:
  name-server: 192.168.20.244:9876 # 自己的RocketMQ服务地址
  producer:
    send-message-timeout: 300000
    group: ch-upms
#====================================mybatis-plus config===============================================
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: com.ch.cloud.upms.model
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      id-type: auto

#====================================custom config===============================================
path:
  root: xxx
  temp: xxx/tmp
  upload: ${path.root}\\upload
  download: share/download

ch:
  gateway: ch-gateway

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
