DROP TABLE IF EXISTS `lt_login_record`;
CREATE TABLE `lt_login_record` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `url` VARCHAR(50) NULL COMMENT '原文件名',
  `method` VARCHAR(255) NOT NULL COMMENT '文件存储相对路径(不包含共享路径)',
  `request` VARCHAR(50) NOT NULL COMMENT '文件名',
  `proxy` VARCHAR(255) NULL COMMENT '文件后缀',
  `response` BIGINT(20) NULL COMMENT '文件大小',
  `permission_code` VARCHAR(255) NULL COMMENT '文件内容类型',
  `username` VARCHAR(255) DEFAULT NULL COMMENT '描述',
  `STATUS` CHAR(1) NOT NULL DEFAULT '0' COMMENT '状态：0.待处理 1.可用 2.拒绝 3.删除 4.异常',
  `CREATE_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATE_BY` VARCHAR(64) NULL COMMENT '创建人',
  PRIMARY KEY (`ID`),
  KEY `IDX_BT_UR_STATUS` (`STATUS`),
  KEY `IDX_BT_UR_CREATE_BY` (`CREATE_BY`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT '日志表-登录记录';