CREATE TABLE `st_role_permission` (
  `ROLE_ID` bigint(20) NOT NULL COMMENT '角色ID',
  `PERMISSION_ID` bigint(20) NOT NULL COMMENT '用户ID',
  PRIMARY KEY (`ROLE_ID`,`PERMISSION_ID`) USING BTREE,
  KEY `IDX_ST_RP_PERMISSION_ID` (`PERMISSION_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='角色权限表';