name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Git branch to build'
        required: true
        default: 'master'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      APP_NAME: ch-upms
      IMG_NAMESPACE: chaohua2025  # 请替换为你的 DockerHub 命名空间
      HUB_ADDR: docker.io

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Configure Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cp .github/maven/settings.xml ~/.m2/settings.xml
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Build with Maven (custom settings.xml)
        run: mvn -s ~/.m2/settings.xml clean package -U -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        

      - name: Set image name
        id: image_name
        run: |
          DATETIME=$(date +'%Y%m%d%H%M%S')
          echo "IMG_NAME=${APP_NAME}:${DATETIME}" >> $GITHUB_ENV
          echo "FULL_IMAGE=${IMG_NAMESPACE}/${APP_NAME}:${DATETIME}" >> $GITHUB_ENV
          
      - name: Extract revision from POM
        id: extract_revision
        run: |
          REVISION=$(mvn help:evaluate -Dexpression=revision -q -DforceStdout)
          echo "Revision is $REVISION"
          JAR_FILE="${APP_NAME}-${REVISION}.jar"
          echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV
          sed -i "s|ARG JAR_FILE=./app.jar|ARG JAR_FILE=./$JAR_FILE|" web/src/main/docker/Dockerfile
          
      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMG_NAME }} -f web/src/main/docker/Dockerfile .
          docker tag ${{ env.IMG_NAME }} ${{ env.FULL_IMAGE }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push ${{ env.FULL_IMAGE }}
          docker rmi ${{ env.FULL_IMAGE }} ${{ env.IMG_NAME }}
